### ISSUE TITLE
Parser bug with multiline comments

### ISSUE THREAD

**Issue by azalty** [sourcemod-dev/docgen#23]
See https://sourcemod.dev/#/menus/enumeration.MenuAction as an example

Website:
![image](https://github.com/sourcemod-dev/docgen/assets/36737524/ddbe31e6-0c53-46d9-8c59-c5f76c9c6fc6)

File:
![image](https://github.com/sourcemod-dev/docgen/assets/36737524/8eac468b-b1e5-4782-bbf8-044c94269ce3)

**Comment by rumblefrog** [comment]
See https://github.com/alliedmodders/sourcemod/pull/1231; known, but since we use spcomp exp parser, this is something to be upstream.
